    [#--bintray integration--]
    [@ww.checkbox labelKey="Bintray configuration (deprecated)" name="bintrayConfiguration" toggle='true'/]
    [@ui.bambooSection dependsOn="bintrayConfiguration"  showOn=true]
        [@ww.textfield name="bintray.subject" labelKey="artifactory.task.pushToBintray.subject"/]
        [@ww.textfield name="bintray.repository" labelKey="artifactory.task.pushToBintray.repository"/]
        [@ww.textfield name="bintray.packageName" labelKey="artifactory.task.pushToBintray.packageName"/]
        [@ww.textfield name="bintray.licenses" labelKey="artifactory.task.pushToBintray.licenses"/]
        [@ww.textfield name="bintray.vcsUrl" labelKey="artifactory.task.pushToBintray.vcsUrl"/]
        [@ww.select name="bintray.signMethod" label="Sign method" list=signMethods listKey='key' listValue='value'/]
        [@ww.textfield name="bintray.gpgPassphrase" labelKey= "GPG Passphrase"/]
    [/@ui.bambooSection]
