package org.jfrog.bamboo.context;

import com.atlassian.bamboo.v2.build.BuildContext;
import org.apache.commons.lang3.StringUtils;

import java.util.Map;

/**
 * Created by Bar Belity on 08/10/2020.
 */
public abstract class ArtifactoryBuildContext {
    public static final String BUILD_NAME = "artifactory.task.buildName";
    public static final String BUILD_NUMBER = "artifactory.task.buildNumber";
    public static final String DEFAULT_BUILD_NAME = "${bamboo.buildPlanName}";
    public static final String DEFAULT_BUILD_NUMBER = "${bamboo.buildNumber}";

    protected final Map<String, String> env;

    public ArtifactoryBuildContext(Map<String, String> env) {
        this.env = env;
    }

    /**
     * Get build name from context.
     * Empty build-name in context occurs when running a task which was configured prior to allowing customizable build name.
     * In this case, return the plan-name generated by Bamboo to allow backward compatibility.
     */
    public String getBuildName(BuildContext buildContext) {
        String buildName = env.get(BUILD_NAME);
        if (StringUtils.isNotBlank(buildName)) {
            return buildName;
        }
        // Extract backward compatible build-name.
        return buildContext.getPlanName();
    }

    /**
     * Get build number from context.
     * Empty build name in context occurs when running a task which was configured prior to allowing customizable build number.
     * In this case, return the build-number generated by Bamboo to allow backward compatibility.
     */
    public String getBuildNumber(BuildContext buildContext) {
        String buildNumber = env.get(BUILD_NUMBER);
        if (StringUtils.isNotBlank(buildNumber)) {
            return buildNumber;
        }
        // Extract backward compatible build-number.
        return String.valueOf(buildContext.getBuildNumber());
    }
}
