    [#--blackduck integration--]
    [@ww.checkbox labelKey='artifactory.task.blackduck.runChecks' name='artifactory.common.blackduck.runChecks' toggle='true'/]
    [@ui.bambooSection dependsOn='artifactory.common.blackduck.runChecks' showOn=true]
        [@ww.textfield labelKey='artifactory.task.blackduck.appName' name='artifactory.common.blackduck.appName' /]
        [@ww.textfield labelKey='artifactory.task.blackduck.appVersion' name='artifactory.common.blackduck.appVersion' /]
        [@ww.textfield labelKey='artifactory.task.blackduck.reportRecipients' name='artifactory.common.blackduck.reportRecipients' /]
        [@ww.textfield labelKey='artifactory.task.blackduck.scopes' name='artifactory.common.blackduck.scopes' /]
        [@ww.checkbox labelKey='artifactory.task.blackduck.includePublishedArtifacts' name='artifactory.common.blackduck.includePublishedArtifacts' toggle='false'/]
        [@ww.checkbox labelKey='artifactory.task.blackduck.autoCreateMissingComponentRequests' name='artifactory.common.blackduck.autoCreateMissingComponentRequests' toggle='true'/]
        [@ww.checkbox labelKey='artifactory.task.blackduck.autoDiscardStaleComponentRequests' name='artifactory.common.blackduck.autoDiscardStaleComponentRequests' toggle='true'/]
    [/@ui.bambooSection]