updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status bambooReleaseGit --context "$step_name"

pipelines:
  - name: release_bamboo
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "8.0.0"
      environmentVariables:
        readOnly:
          NEXT_VERSION: 0.0.0
          NEXT_DEVELOPMENT_VERSION: 0.0.x-SNAPSHOT

    steps:
      - name: Release
        type: Bash
        configuration:
          inputResources:
            - name: bambooReleaseGit
          integrations:
            - name: releases_temp
            - name: github_generic
        execution:
          onStart:
            - *UPDATE_COMMIT_STATUS
            - restore_cache_files m2_home ${HOME}/.m2
          onExecute:
            - cd $res_bambooReleaseGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_CLI_BUILD_NAME=bamboo-artifactory-plugin
            - export JFROG_CLI_BUILD_NUMBER=$run_number
            # Set M2_HOME
            - MVN_PATH=`which mvn` && export M2_HOME=`readlink -f $MVN_PATH | xargs dirname | xargs dirname`

            # Configure git
            - git checkout release
            - git remote set-url origin https://$int_github_generic_token@github.com/jfrog/bamboo-artifactory-plugin.git

            # Make sure versions provided
            - echo "Checking variables"
            - test -n "$NEXT_VERSION" -a "$NEXT_VERSION" != "0.0.0"
            - test -n "$NEXT_DEVELOPMENT_VERSION" -a "$NEXT_DEVELOPMENT_VERSION" != "0.0.x-SNAPSHOT"

            # Download JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog

            # Configure JFrog CLI
            - ./jfrog c add releases --artifactory-url=https://releases.jfrog.io/artifactory --access-token=$int_releases_temp_token
            - ./jfrog rt mvnc
              --server-id-deploy releases --repo-deploy-releases oss-release-local --repo-deploy-snapshots oss-snapshot-local

            # Sync changes with master
            - git merge origin/master

            # Update version
            - env -i PATH=$PATH M2_HOME=$M2_HOME HOME=$HOME mvn versions:set -DnewVersion="${NEXT_VERSION}" -B
            - git commit -am "[artifactory-release] Release version ${NEXT_VERSION} [skipRun]" --allow-empty
            - git tag ${NEXT_VERSION}
            - git push
            - git push --tags

            # Run install and publish
            - >
              env -i PATH=$PATH M2_HOME=$M2_HOME HOME=$HOME
              ./jfrog rt mvn clean install -U -B

            # Update next development version
            - env -i PATH=$PATH M2_HOME=$M2_HOME HOME=$HOME mvn versions:set -DnewVersion=$NEXT_DEVELOPMENT_VERSION -B
            - git commit -am "[artifactory-release] Next development version [skipRun]"
            - git push

            # Merge changes to master
            - git checkout master
            - git merge origin/release
            - git push

          onComplete:
            # Show tests in the *Tests* tab
            - save_tests $res_bambooReleaseGit_resourcePath/target/surefire-reports/

            - *UPDATE_COMMIT_STATUS

            # Save .m2 cache
            - add_cache_files ${HOME}/.m2 m2_home